### PR TITLE
Match optional space inside the GPU model number

### PR DESCRIPTION
**Pull request by Oletus**
We've seen samples of prefixed GPU model numbers given with both a space inside and no space inside. Examples:

Radeon Pro WX3200 vs.
Radeon Pro WX 3200

Change the name matching algorithm so that the version number may contain a short uppercase prefix and so that there's an optional space between the prefix and the digits.

### CODE REVIEW

**Comment by Oletus** [comment]
This patch comes courtesy of Higharc! @gkjohnson this should be useful at least for matching names correctly between different data sources.

**Comment by gkjohnson** [comment]
Thanks! Good find. I've run through a few test cases of hypothetical gpu name scenarios using the global `findNameMatch` function I added to the example page:

**master branch**

| | `Radeon Pro WX3200` | `Radeon Pro WX 3200` | `Radeon Pro 3200` |
|---|---|---|---|
| `Radeon Pro WX3200` | - | fail | fail |
| `Radeon Pro WX 3200` | fail | - | 0.999 |
| `Radeon Pro 3200` | fail | 0.999 | - |

**this branch**

| | `Radeon Pro WX3200` | `Radeon Pro WX 3200` | `Radeon Pro 3200` |
|---|---|---|---|
| `Radeon Pro WX3200` | - | 0.96546... | fail |
| `Radeon Pro WX 3200` | 0.96546... | - | fail |
| `Radeon Pro 3200` | fail | 0.999 | - |

A couple things:

- One GPU pair that was formerly passing is now failing to match
- The matching is now asymmetric in some cases:

```js
findNameMatch('Radeon Pro WX 3200', ['Radeon Pro 3200']); // fails
findNameMatch('Radeon Pro 3200', ['Radeon Pro WX 3200']); // score: 0.999
```

So it now matters which gpu is the first argument. I _think_ it didn't matter previously and this function is used for merging GPUs from the different data sources so I think it's relatively important that the score not be argument order dependent that way.

In my mind `Radeon Pro WX3200` should be able to match with `Radeon Pro 3200`, as well, but it should be given a lower score so a priority is given to those GPUs with `WX` in the name. How do you feel about tokenizing numbers separately from letters in `strToCompareArray` so both "Radeon Pro WX3200" and "Radeon Pro WX 3200" become the array `[ 'Radeon', 'Pro', 'WX', '3200' ]`? I'm also trying to recall if there was a good reason why the "versionMatches" regex was set to `/\w*\d\d\d+\w*/` rather than just `/\d\d\d+/`. Perhaps that can be changed, as well?

**Comment by Oletus** [comment]
I added a commit fixing the symmetry issues, making the matching a bit more lenient.

I think the code is a bit more robust if the suffix used after the number is included in versionRegexp, there are GPU names like Radeon R9 285X which is different from Radeon R9 285.

Tokenizing numbers from letters separately might work, but we could hit some false matches with that as well, and I guess there'd be a small performance hit.

**Comment by gkjohnson** [comment]
I ran an the script to generate [the markdown file list of matches](https://github.com/gkjohnson/webgl-gpu-power-estimation/blob/master/data/MATCHES.md) with this PR if you want to take a look at how it changed compared to master:

https://github.com/gkjohnson/webgl-gpu-power-estimation/compare/683ebf6..69ec813

Looking over it briefly it doesn't look like anything too radical changed. And here's the new table:

| | `Radeon Pro WX3200` | `Radeon Pro WX 3200` | `Radeon Pro 3200` |
|---|---|---|---|
| `Radeon Pro WX3200` | - | 0.96546... | 0.66466... |
| `Radeon Pro WX 3200` | 0.96546... | - | 0.999... |
| `Radeon Pro 3200` | 0.66466... | 0.999... | - |

Looks good!

> Tokenizing numbers from letters separately might work, but we could hit some false matches with that as well, and I guess there'd be a small performance hit.

If performance becomes an issue maybe it's worth looking at how it can be sped but it seems pretty quick right now and only has to be run once on the client. And I think tokenizing the letters separately from digits will actually give better matches. In the above table `Radeon Pro WX 3200` matches `Radeon Pro WX3200` with a score of 0.96... while it matches `Radeon Pro 3200` with a score of 0.99... I would expect those to actually be reversed and I believe this adjustment would fix that. What are your thoughts?

**Comment by Oletus** [comment]
I think the scoring could be adjusted by giving more weight to unmatched tokens, or scoring a match between "WX 3200" and "WX3200" tokens 0.999 instead of 0.9 as it is now. I'm still a bit doubtful about the benefits of tokenizing digits separately because under that scheme "285" would be considered an almost perfect match with "285X" if the system otherwise remains as it is.

**Comment by Oletus** [comment]
I added a commit adjusting the weighting.

**Comment by gkjohnson** [comment]
I added a new function to utils that logs these tables in the example page if you find them useful:

```js
toScoreTable(['Radeon Pro WX3200', 'Radeon Pro WX 3200', 'Radeon Pro 3200']);
```

Looks like it added conflicts so sorry about that 😬. It looks like your last commit changed line endings or something because every line is different in this PR -- my changes didn't touch any of the functions you've been working on, though. Here's the new table:

| | Radeon Pro WX3200 | Radeon Pro WX 3200 | Radeon Pro 3200 |
|---|---|---|---|
| **Radeon Pro WX3200** | - | 0.9918 | 0.6467 |
| **Radeon Pro WX 3200** | 0.9918 | - | 0.9900 |
| **Radeon Pro 3200** | 0.6467 | 0.9900 | - |

Looks like they match in the order I'd expect them to now.

> I'm still a bit doubtful about the benefits of tokenizing digits separately because under that scheme "285" would be considered an almost perfect match with "285X" if the system otherwise remains as it is.

I do see what you're saying now. This might come down to wanting a stricter name matching policy when matching names to create the database compared to matching them in the browser. When creating the database you wouldn't want `Pro 3200` to match with `Pro WX3200` because you can be reasonably sure they're different cards and should get different entries. But when matching the unmasked renderer field you'd probably be okay if `Pro WX3200` matched `Pro 3200` if a higher quality match like `WX 3200` doesn't exist in the database.

Hopefully that made sense. Either way I think this is an improvement so once the conflicts are addressed I'll merge!

**Comment by Oletus** [comment]
Force-pushed an amended version of the last commit with just the line endings fixed. Thanks for reviewing this!

**Comment by Oletus** [comment]
@gkjohnson Friendly ping, this should be ready to merged!

**Comment by gkjohnson** [comment]
Thanks for the ping -- it's been a busy week!

**Comment by gkjohnson** [comment]
Thanks!

**Pull request merged**
